### ISSUE TITLE
Overriding localization strings

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#1059]
I create my own plugin which extends RainLab.User plugin and I would like to change menu string from "Users" to "Clients".

I followed documentation https://octobercms.com/docs/plugin/localization#overriding , but with no luck.

I created folder /lang/rainlab/user/en/lang.php in my project root with code

    return [
        'users' => [
            'menu_label' => 'Clients',
            'all_users'  => 'All Clients',
        ]
    ];

I even tried to place this file into /plugins/my_namespace/my_plugin_name/lang/rainlab/user/en/lang.php, but with no luck either.

Something is not working or documentation is wrong.

**Comment by mpopke** [comment]
I would change this to confirmed bug. I'm having the exact same problem with a different plugin. I've done exactly what the documentation says, and it just is not working. Either the documentation is wrong or there is a bug here.

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/library/pull/108

**Comment by alvaro-canepa** [comment]
This issue is not fixed. Or the documentation was wrong. The method `\October\Rain\Translation\FileLoader::loadNamespaceOverrides` get a file like this (using the User plugin as example)

    /lang/
      rainlab.user/
        en/
          lang.php

instead of

    /lang/
      rainlab/
        user/
            en/
                lang.php


Thanks

**Comment by daftspunk** [comment]
Correct approach is:

```
lang/
  en/
    rainlab/
      user/
        lang.php
```

Updated code and docs to reflect this. Thanks for reporting this
