### ISSUE TITLE
Add Horizontal Scrolling Feature for Backend Navbar

### ISSUE THREAD

**Issue by kdoonboli** [octobercms/october#1873]
In the admin backend navbar, if you have too many plugins, it won't scroll horizontally. I have to manually resize the window to see the rest of the icons on top.

**Comment by jBOKA** [comment]
You can drag and drop the whole bar horizontally to move the icons.

**Comment by daftspunk** [comment]
Fixed in `stable` branch already. You can scroll (horizontal or vertical) or drag the menu.

**Comment by kdoonboli** [comment]
uhh. I see it working now! Thanks bud :+1:

**Comment by KiszNa** [comment]
@daftspunk I have followed https://github.com/octobercms/october/commit/27d32d35ea84b481dfd5b39c0fcf23fffeedcb3f 
but still doesn't work in my case.
