### ISSUE TITLE
getThumb doesn't take EXIF rotation into account

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1942]
Shouldn't the `getThumb` method take EXIF rotation of pictures into account?
Since it strips the infomation away, it's doesn't make sense to argue that the responsibility is on the browsers side to display the picture correctly.

I think the rotation should occur before any other manipulations are applied to the image. Any objections?
edit:
Or maybe for efficiency reasons, the rotation should occur after the resizing, which would raise some requirements for the `mode`'s width and height calculations.

**Comment by estudiogenius** [comment]
Any advance with this??

**Comment by daftspunk** [comment]
Can someone submit a PR that addresses this?

**Comment by jBOKA** [comment]
I prepared everything. Unfortunately I found EXIF data in general to be very buggy. So this won't fix the whole thing since I could just `exif_read_data` which failed some attempts.

In case the PHP exif extension is not present, the Resizer now pretty much skips the rotation.

Might be there are some obvious memory flaws in my logic regarding passing the image around between the methods, please check the code...

https://github.com/octobercms/library/pull/240

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/library/pull/240

Great job @jBOKA!

**Comment by robinbonnes** [comment]
Could it be that this is still not fully working?

I replaced the Resizer.php class on my october install, and tried uploading a portrait image. The image (and thumbnail) are correctly generated, but on the webpage it still shows the image turned 90 degrees to landscape. When I browse to the image url directly in the browser it is correctly shown in portrait.

When I open the image (made with an iPad) in Photoshop, and simply save and upload it, it is shown correct.

**Comment by jBOKA** [comment]
The implementation only does a rotation on thumb generation using the `getThumb` method. Have you tried that?

If you only use `getPath` or click on the *Attachment URL* link in the backend popup for attachments, you will see the original unrotated version as uploaded. In that case you have to be aware that browsers might or might not take the exif data into account. So when opening the file directly (not the generated thumb file), you rely solely on browsers which may vary in automatic rotation support.

**Comment by robinbonnes** [comment]
That makes things clear. Indeed, the thumbnail is rotated, but not the original. 

I also saw a CSS alternative:

img {
    image-orientation: from-image;
}

But this is not (yet) supported in all major browsers.

I tried the getThumb(0,0) workaround and this works! Thanks.

For people interested:

I was using the RJGallery plugin, and to fix this I have overwritten the gallery component default.htm in my theme partials folder: /theme/{themename}/gallery/default.htm and replaced this part:

<div style="width:100%">
    <ul id="{{ __SELF__ }}" class="{{ __SELF__ }}">
        {% for image in gallery.images %}
            <li data-src="{{ image.path }}" data-title="{{ image.title }}" data-desc="{{ image.description }}">
                <a href="#"><img src="{{ image.getThumb(width, height, resizer) }}" alt="{{ image.title }}" /></a>
            </li>
        {% endfor %}
    </ul>
</div>

With this:

<div style="width:100%">
    <ul id="{{ __SELF__ }}" class="{{ __SELF__ }}">
        {% for image in gallery.images %}
            <li data-src="{{ image.getThumb(0,0) }}" data-title="{{ image.title }}" data-desc="{{ image.description }}">
                <a href="#"><img src="{{ image.getThumb(width, height, resizer) }}" alt="{{ image.title }}" /></a>
            </li>
        {% endfor %}
    </ul>
</div>

**Comment by jBOKA** [comment]
@daftspunk I can add a remark about the rotation to the docs but I don't know when the rain library changes can be considered as deployed to the installer/composer version

**Comment by robinbonnes** [comment]
Nope, its not completely working yet. For some images, when I change image.getPath to image.getThumb(0,0), both the frontend and backend crashes. It doesn't show any error message, but when I enter the frontend page, the complete page source exists out of:

```
<div style="width:100%">
    <ul id="gallery" class="gallery">
                                            <li data-src="
```

I will investigate it further...

**Comment by jBOKA** [comment]
If this happens with only certain images, post them here so I can also look
into it

robinbonnes <notifications@github.com> schrieb am Do., 27. Okt. 2016, 22:37:

**Comment by daftspunk** [comment]
Are there different versions of EXIF or something like this?

**Comment by jBOKA** [comment]
Not that i know of. It's been around for about 20 years. No major changes since then. I guess it might be due to camera manufacturers not sticking to the standard. But I have no idea what might be causing that total crash of the resizer. I thought I covered the most probable points for exceptions.

**Comment by robinbonnes** [comment]
Sorry @jBOKA forgot to post the image. Here it is:

![tree](https://cloud.githubusercontent.com/assets/5117166/19951327/9ffcdc18-a15d-11e6-8953-457b23755f0e.jpg)

Can you try to upload this to OctoberCMS, for example with the RJGallery?

**Comment by jBOKA** [comment]
@robinbonnes just set up a new clean october install and didn't have any issues rendering your image. Here's the result:
http://rotation.ohdev.de/storage/app/uploads/public/581/b5a/2fd/thumb_2_400x400_0_0_auto.jpg
Also shows up correctly directly in HTML/page context.
Here the `getThumb(0,0)` version
http://rotation.ohdev.de/storage/app/uploads/public/581/b5a/2fd/thumb_2_0x0_0_0_auto.jpg

Can you provide more information, like PHP version etc.? This seems like a webserver configuration issue.
I just tried without issues in two different linux environments using PHP 5.6.27. Can you check for your webserver errors or something?

**Comment by robinbonnes** [comment]
On the production server I use PHP version 7.0.12. 

When I show the page containing a gallery (RJGallery) with multiple images (including above 2), the source of the page shows me the following:

```
<div style="width:100%">
    <ul id="gallery" class="gallery">
                    <li data-src="/storage/app/uploads/public/580/cfa/083/thumb_48_0x0_0_0_auto.jpg" data-title="" data-desc="">
                <a href="#"><img src="/storage/app/uploads/public/580/cfa/083/thumb_48_100x70_0_0_auto.jpg" alt="" /></a>
            </li>
                    <li data-src="      
```

As you can see it breaks on the second image in the gallery and the complete page source only shows me the partial content.

I checked the PHP log file and it shows me the following:

Backend fatal error: PHP Fatal error:  Allowed memory size of 100663296 bytes exhausted (tried to allocate 73728 bytes) in /public_html/vendor/composer/ClassLoader.php on line 412.

And:

Backend fatal error: PHP Fatal error:  Allowed memory size of 100663296 bytes exhausted (tried to allocate 32768 bytes) in /public_html/vendor/symfony/debug/Exception/FatalErrorException.php on line 1.

This makes sense to me, it probably can't create all the fullsize thumbs for multiple images because it exceeds the memory limit?

**Comment by jBOKA** [comment]
I already thought it might be a memory issue. @daftspunk I came across this earlier on a shared hoster, when I tested the sharpening implementation of the resizer. Do you think there's a way to reduce the memory usage?

I will test some things tomorrow if I find the time. Maybe some refactoring might help.

**Comment by jBOKA** [comment]
I tried to replicate the issue, tested with PHP `memory_limit = 20M` and several almost 10MB jpegs, including simultaneous sharpening and rotation with full size settings... no issues.

Since your memory limit is set to about 100M, there must be another problem. Can you trace it down to a certain file, or do these errors come up on every thumb creation?

**Comment by robinbonnes** [comment]
It really has something to do with the .getThumb(0,0) function in combination with bigger sized images. This code is working (because the getThumb parameters are not (0, 0):

```
        {% for image in gallery.images %}
            <li data-src="{{ image.getPath }}" data-title="{{ image.title }}" data-desc="{{ image.description }}">
                <a href="#"><img src="{{ image.getThumb(width, height, resizer) }}" alt="{{ image.title }}" /></a>
            </li>
        {% endfor %}
```

But this isn't:

```
        {% for image in gallery.images %}
            <li data-src="{{ image.getThumb(0,0) }}" data-title="{{ image.title }}" data-desc="{{ image.description }}">
                <a href="#"><img src="{{ image.getThumb(width, height, resizer) }}" alt="{{ image.title }}" /></a>
            </li>
        {% endfor %}
```

I think it has something to do with the size of the images. Most of the images are around 1/2/3 MB. When I reorder the gallery in the backend (so it creates the thumbs in a different order), the frontend page is crashing on the bigger sized images (2/3 MB). I also had one page with images only under 2 MB and this is working fine.

Unfortunately I can't increase the PHP memory limit because I'm on a shared hosting.

So I think it isn't related to rotating the image. Maybe its just consuming to much memory, because in fact it generates the thumbnails for each image twice (full size and thumbnail). Maybe this rotation part should be implemented on uploading? Then it doesn't have to be done on creating thumbnails.

**Comment by jBOKA** [comment]
I can't imagine October to use 100M memory. You know what, try the attached Resizer.php on your shared hosting. I just added lots of Log entries all over the resize function.
You can check the Log in `/backend/system/eventlogs`

I assume your memory must already be pretty full. In my case the memory usage doesn't raise in a mentionable way while resizing.

Reiszer.php
```
<?php namespace October\Rain\Database\Attach;

use File as FileHelper;
use Symfony\Component\HttpFoundation\File\File as FileObj;
use Exception;

/**
 * Image resizer
 *
 * Usage:
 *      Resizer::open(mixed $file)
 *          ->resize(int $width , int $height, string 'exact, portrait, landscape, auto or crop')
 *          ->save(string 'path/to/file.jpg', int $quality);
 *
 *      // Resize and save an image.
 *      Resizer::open(Input::file('field_name'))
 *          ->resize(800, 600, 'crop')
 *          ->save('path/to/file.jpg', 100);
 *
 *      // Recompress an image.
 *      Resizer::open('path/to/image.jpg')
 *          ->save('path/to/new_image.jpg', 60);
 *
 * @package october\database
 * @author Alexey Bobkov, Samuel Georges
 */
class Resizer
{
    /**
     * @var Resource The symfony uploaded file object.
     */
    protected $file;

    /**
     * @var Resource The extension of the uploaded file.
     */
    protected $extension;

    /**
     * @var Resource The image (on disk) that's being resized.
     */
    protected $image;

    /**
     * @var Resource The cached, original image.
     */
    protected $originalImage;

    /**
     * @var int Original width of the image being resized.
     */
    protected $width;
    
    /**
     * @var int Original height of the image being resized.
     */
    protected $height;

    /**
     * @var int|null Exif orientation of image
     */
    protected $orientation;

    /**
     * @var array Array of options used for resizing.
     */
    protected $options = [];

    /**
     * Instantiates the Resizer and receives the path to an image we're working with
     * @param mixed $file The file array provided by Laravel's Input::file('field_name') or a path to a file
     */
    function __construct($file)
    {
        \Log::info('00 construct resizer (image: '.$file.'): '.memory_get_usage());
        if (!extension_loaded('gd')) {
            echo 'GD PHP library required.'.PHP_EOL;
            exit(1);
        }

        if (is_string($file)) {
            $file = new FileObj($file);
        }

        // Get the file extension
        $this->extension = $file->guessExtension();

        // Open up the file
        $this->image = $this->originalImage = $this->openImage($file);

        // Get width and height of our image
        $this->orientation  = $this->getOrientation($file);

        // Get width and height of our image
        $this->width  = $this->getWidth();
        $this->height = $this->getHeight();

        // Set default options
        $this->setOptions([]);
    }

    /**
     * Static call, Laravel style.
     * Returns a new Resizer object, allowing for chainable calls
     * @param  mixed $file The file array provided by Laravel's Input::file('field_name') or a path to a file
     * @return Resizer
     */
    public static function open($file)
    {
        return new Resizer($file);
    }

    /**
     * Resets the image back to the original.
     * @return self
     */
    public function reset()
    {
        $this->image = $this->originalImage;

        return $this;
    }

    /**
     * Sets resizer options. Available options are:
     *  - mode: Either exact, portrait, landscape, auto or crop.
     *  - offset: The offset of the crop = [ left, top ]
     *  - sharpen: Sharpen image, from 0 - 100 (default: 0)
     *  - quality: Image quality, from 0 - 100 (default: 95)
     * @return self
     */
    public function setOptions($options)
    {
        $this->options = array_merge([
            'mode'    => 'auto',
            'offset'  => [0, 0],
            'sharpen' => 0,
            'quality' => 95
        ], $options);

        return $this;
    }

    /**
     * Sets an individual resizer option.
     * @return self
     */
    protected function setOption($option, $value)
    {
        $this->options[$option] = $value;

        return $this;
    }

    /**
     * Gets an individual resizer option.
     * @return self
     */
    protected function getOption($option)
    {
        return array_get($this->options, $option);
    }

    /**
     * Receives the image's exif orientation
     * @return int|null
     */
    protected function getOrientation($file)
    {
        $mime = $file->getMimeType();
        $filePath = $file->getPathname();

        if ($mime != 'image/jpeg' || !function_exists('exif_read_data')) {
            return null;
        }

        /*
         * Reading the exif data is prone to fail due to bad data
         */
        try {
            $exif = exif_read_data($filePath);
        }
        catch (Exception $e) {
            return null;
        }

        if (!isset($exif['Orientation'])) {
            return null;
        }

        // Only take care of spin orientations, no mirrored
        if (!in_array($exif['Orientation'], [1, 3, 6, 8], true)) {
            return null;
        }

        return $exif['Orientation'];
    }

    /**
     * Receives the image's width while respecting
     * the exif orientation
     * @return int
     */
    protected function getWidth()
    {
        switch ($this->orientation) {
            case 6:
            case 8:
                return imagesy($this->image);

            case 1:
            case 3:
            default:
                return imagesx($this->image);
        }
    }

    /**
     * Receives the image's height while respecting
     * the exif orientation
     * @return int
     */
    protected function getHeight()
    {
        switch ($this->orientation) {
            case 6:
            case 8:
                return imagesx($this->image);

            case 1:
            case 3:
            default:
                return imagesy($this->image);
        }
    }

    /**
     * Receives the original but rotated image
     * according to exif orientation
     * @return resource (gd)
     */
    protected function getRotatedOriginal()
    {
        \Log::info('1 start rotate: '.memory_get_usage());

        switch ($this->orientation) {
            case 6:
                $angle = 270.0;
                break;

            case 8:
                $angle = 90.0;
                break;

            case 3:
                $angle = 180.0;
                break;

            case 1:
            default:
                return $this->image;
        }

        $bgcolor = imagecolorallocate($this->image, 0, 0, 0);
        $rotatedOriginal = imagerotate($this->image,$angle,$bgcolor);
        \Log::info('2 end rotate: '.memory_get_usage());

        return $rotatedOriginal;
    }

    /**
     * Resizes and/or crops an image
     * @param int $newWidth The width of the image
     * @param int $newHeight The height of the image
     * @param array $options A set of resizing options, supported values:
     * @return self
     */
    public function resize($newWidth, $newHeight, $options = [])
    {
        $this->setOptions($options);

        \Log::info('0 start resize: '.memory_get_usage());

        /*
         * Sanitize input
         */
        $newWidth = (int) $newWidth;
        $newHeight = (int) $newHeight;

        if (!$newWidth && !$newHeight) {
            $newWidth = $this->width;
            $newHeight = $this->height;
        }
        elseif (!$newWidth) {
            $newWidth = $this->getSizeByFixedHeight($newHeight);
        }
        elseif (!$newHeight) {
            $newHeight = $this->getSizeByFixedWidth($newWidth);
        }

        // Get optimal width and height - based on supplied mode.
        list($optimalWidth, $optimalHeight) = $this->getDimensions($newWidth, $newHeight);

        // Resample - create image canvas of x, y size
        $imageResized = imagecreatetruecolor($optimalWidth, $optimalHeight);

        // Retain transparency for PNG and GIF files
        imagecolortransparent($imageResized, imagecolorallocatealpha($imageResized, 0, 0, 0, 127));
        imagealphablending($imageResized, false);
        imagesavealpha($imageResized, true);

        // get the rotated the original image according to exif orientation
        $rotatedOriginal = $this->getRotatedOriginal();
        \Log::info('3 after rotate: '.memory_get_usage());

        // Create the new image
        imagecopyresampled($imageResized, $rotatedOriginal, 0, 0, 0, 0, $optimalWidth, $optimalHeight, $this->width, $this->height);

        $this->image = $imageResized;

        /*
         * Apply sharpness
         */
        if ($sharpen = $this->getOption('sharpen')) {
            $this->sharpen($sharpen);
        }

        /*
         * If mode is crop: find center and use for the cropping.
         */
        if ($this->getOption('mode') == 'crop') {
            $offset = $this->getOption('offset');
            $cropStartX = ($optimalWidth  / 2) - ($newWidth  / 2) - $offset[0];
            $cropStartY = ($optimalHeight / 2) - ($newHeight / 2) - $offset[1];
            $this->crop($cropStartX, $cropStartY, $newWidth, $newHeight);
        }
        \Log::info('4 end resize: '.memory_get_usage());

        return $this;
    }

    /**
     * Sharpen the image across a scale of 0 - 100
     * @param int $sharpness
     * @return self
     */
    public function sharpen($sharpness)
    {
        if ($sharpness <= 0 || $sharpness > 100) {
            return $this;
        }

        $image = $this->image;

        // Normalize sharpening value
        $kernelCenter = exp((80 - floatval($sharpness)) / 18) + 9;

        $matrix = array(
            [-1, -1, -1],
            [-1, $kernelCenter, -1],
            [-1, -1, -1],
        );

        $divisor = array_sum(array_map('array_sum', $matrix));

        imageconvolution($image, $matrix, $divisor, 0);

        $this->image = $image;

        return $this;
    }

    /**
     * Crops an image from its center
     * @param int $cropStartX Start on X axis
     * @param int $cropStartY Start on Y axis
     * @param int $newWidth The new width
     * @param int $newHeight The new height
     * @param int $srcWidth Source area width.
     * @param int $srcHeight Source area height.
     * @return self
     */
    public function crop($cropStartX, $cropStartY, $newWidth, $newHeight, $srcWidth = null, $srcHeight = null)
    {
        $image = $this->image;

        if ($srcWidth === null) {
            $srcWidth = $newWidth;
        }
        if ($srcHeight === null) {
            $srcHeight = $newHeight;
        }

        // Create a new canvas
        $imageResized = imagecreatetruecolor($newWidth, $newHeight);

        // Retain transparency for PNG and GIF files
        imagecolortransparent($imageResized, imagecolorallocatealpha($imageResized, 0, 0, 0, 127));
        imagealphablending($imageResized, false);
        imagesavealpha($imageResized, true);

        // Crop the  image to the requested size
        imagecopyresampled($imageResized, $image, 0, 0, $cropStartX, $cropStartY, $newWidth, $newHeight, $srcWidth, $srcHeight);

        $this->image = $imageResized;

        return $this;
    }

    /**
     * Save the image based on its file type.
     * @param string $savePath Where to save the image
     * @return boolean
     */
    public function save($savePath)
    {
        \Log::info('5 start save: '.memory_get_usage());

        $image = $this->image;

        $imageQuality = $this->getOption('quality');

        // Determine the image type from the destination file
        $extension = FileHelper::extension($savePath) ?: $this->extension;

        // Create and save an image based on it's extension
        switch (strtolower($extension)) {
            case 'jpg':
            case 'jpeg':
                // Check JPG support is enabled
                if (imagetypes() & IMG_JPG) {
                    imagejpeg($image, $savePath, $imageQuality);
                }
                break;

            case 'gif':
                // Check GIF support is enabled
                if (imagetypes() & IMG_GIF) {
                    imagegif($image, $savePath);
                }
                break;

            case 'png':
                // Scale quality from 0-100 to 0-9
                $scaleQuality = round(($imageQuality / 100) * 9);

                // Invert quality setting as 0 is best, not 9
                $invertScaleQuality = 9 - $scaleQuality;

                // Check PNG support is enabled
                if (imagetypes() & IMG_PNG) {
                    imagepng($image, $savePath, $invertScaleQuality);
                }
                break;

            default:
                throw new Exception(sprintf('Invalid image type: %s. Accepted types: jpg, gif, png.', $extension));
                break;
        }

        // Remove the resource for the resized image
        imagedestroy($image);
    }

    /**
     * Open a file, detect its mime-type and create an image resource from it.
     * @param array $file Attributes of file from the $_FILES array
     * @return mixed
     */
    protected function openImage($file)
    {
        $mime = $file->getMimeType();
        $filePath = $file->getPathname();

        switch ($mime) {
            case 'image/jpeg': $img = @imagecreatefromjpeg($filePath); break;
            case 'image/gif':  $img = @imagecreatefromgif($filePath);  break;
            case 'image/png':  $img = @imagecreatefrompng($filePath);  break;

            default:
                throw new Exception(sprintf('Invalid mime type: %s. Accepted types: image/jpeg, image/gif, image/png.', $mime));
                break;
        }

        return $img;
    }

    /**
     * Return the image dimensions based on the option that was chosen.
     * @param int $newWidth The width of the image
     * @param int $newHeight The height of the image
     * @param string $option Either exact, portrait, landscape, auto or crop.
     * @return array
     */
    protected function getDimensions($newWidth, $newHeight)
    {
        $mode = $this->getOption('mode');

        switch ($mode) {
            case 'exact':
                return [$newWidth, $newHeight];

            case 'portrait':
                return [$this->getSizeByFixedHeight($newHeight), $newHeight];

            case 'landscape':
                return [$newWidth, $this->getSizeByFixedWidth($newWidth)];

            case 'auto':
                return $this->getSizeByAuto($newWidth, $newHeight);

            case 'crop':
                return $this->getOptimalCrop($newWidth, $newHeight);

            default:
                throw new Exception('Invalid dimension type. Accepted types: exact, portrait, landscape, auto, crop.');
        }
    }

    /**
     * Returns the width based on the image height
     * @param int $newHeight The height of the image
     * @return int
     */
    protected function getSizeByFixedHeight($newHeight)
    {
        $ratio = $this->width / $this->height;
        $newWidth = $newHeight * $ratio;

        return $newWidth;
    }

    /**
     * Returns the height based on the image width
     * @param int $newWidth The width of the image
     * @return int
     */
    protected function getSizeByFixedWidth($newWidth)
    {
        $ratio = $this->height / $this->width;
        $newHeight = $newWidth * $ratio;

        return $newHeight;
    }

    /**
     * Checks to see if an image is portrait or landscape and resizes accordingly.
     * @param int $newWidth  The width of the image
     * @param int $newHeight The height of the image
     * @return array
     */
    protected function getSizeByAuto($newWidth, $newHeight)
    {
        // Less than 1 pixel height and width? (revert to original)
        if ($newWidth <= 1 && $newHeight <= 1) {
            $newWidth = $this->width;
            $newHeight = $this->height;
        }
        elseif ($newWidth <= 1) {
            $newWidth = $this->getSizeByFixedHeight($newHeight);
        }
        // Less than 1 pixel height? (portrait)
        elseif ($newHeight <= 1) {
            $newHeight = $this->getSizeByFixedWidth($newWidth);
        }

        // Image to be resized is wider (landscape)
        if ($this->height < $this->width) {
            $optimalWidth = $newWidth;
            $optimalHeight = $this->getSizeByFixedWidth($newWidth);
        }
        // Image to be resized is taller (portrait)
        elseif ($this->height > $this->width) {
            $optimalWidth = $this->getSizeByFixedHeight($newHeight);
            $optimalHeight = $newHeight;
        }
        // Image to be resized is a square
        else {
            if ($newHeight < $newWidth) {
                $optimalWidth = $newWidth;
                $optimalHeight = $this->getSizeByFixedWidth($newWidth);
            }
            elseif ($newHeight > $newWidth) {
                $optimalWidth = $this->getSizeByFixedHeight($newHeight);
                $optimalHeight = $newHeight;
            }
            else {
                // Square being resized to a square
                $optimalWidth = $newWidth;
                $optimalHeight = $newHeight;
            }
        }

        return [$optimalWidth, $optimalHeight];
    }

    /**
     * Attempts to find the best way to crop. Whether crop is based on the
     * image being portrait or landscape.
     * @param int $newWidth  The width of the image
     * @param int $newHeight The height of the image
     * @return array
     */
    protected function getOptimalCrop($newWidth, $newHeight)
    {
        $heightRatio = $this->height / $newHeight;
        $widthRatio  = $this->width /  $newWidth;

        if ($heightRatio < $widthRatio) {
            $optimalRatio = $heightRatio;
        }
        else {
            $optimalRatio = $widthRatio;
        }

        $optimalHeight = $this->height / $optimalRatio;
        $optimalWidth  = $this->width  / $optimalRatio;

        return [$optimalWidth, $optimalHeight];
    }
}
```

**Comment by robinbonnes** [comment]
Thanks for the support. I've replaced the Resizer class and this is the result:

![image](https://cloud.githubusercontent.com/assets/5117166/20122697/09c3a0ee-a61a-11e6-99ee-7a4356f74c6c.png)

What I did:

- Change the getPath() function with getThumb(0,0)
- Open the page (frontend)
- Change the view order of the images in the backend
- Open the page (frontend)

So in total I tried two times. The first time the page went stuck on the second image. The second time it went stuck on the 6th image. Those images correspond to the ones mentioned in the log. So if I'm right it has something to do with the resizing? But why does it resize only these two images and not the others?

Also: Doesn't it make sense at all to move the image rotation part to the moment after uploading the image? Then rotation doesn't matter anymore for generating the thumbnails, because it will be already in the correct orientation. Also then simply the getPath() function can be used.

**Comment by jBOKA** [comment]
The resizer crashes before rotation. I wonder why it doesn't crash with the old version, if it does. Since I cannot reproduce it's too time consuming. Maybe I can find a shared hoster with a similar problem.

...

Rotation up front would unnecessarily alter the original image, eg strip exif, recompress etc

`getThumb` allows for "live" creation of thumbs. You don't want to deliver full size images to the frontend for bandwidth reasons. And you will need different sizes for different occurrences in the frontend.

**Comment by jBOKA** [comment]
I could reproduce the memory issues on a shared hoster.
Since we carry around several copies memory usage looks like this for a ~4000x2000 image:
`Resizer on __construct`
16M
`@imagecreatefromjpeg($filePath);`
58M
`$imageResized = imagecreatetruecolor($optimalWidth, $optimalHeight);`
100M

then it crashes on 
`$bgcolor = imagecolorallocate($this->image, 0, 0, 0);`

The rotation definitely adds to the memory.

@daftspunk there are two ways to handle this. Try to lower the memory usage by giving up some OOP structure (try to put every intermediate manipulation directly into the `->image` property) or do a memory check upfront?

Since I couldn't even see the memory usage on my apache/php installation, the memory check might not even work.

**Comment by robinbonnes** [comment]
Strange, for me the Resizer class crashes in the resize function on:

$imageResized = imagecreatetruecolor($optimalWidth, $optimalHeight);

I think this difference depends on the size of the image and the memory available. 

So in conclusion, this does mean that the PHP image functions simply consume too much memory (only for images that need resizing)?

**Comment by jBOKA** [comment]
Yup the memory. While resizing/rotating several images are stored in memory
uncompressed. Of course there's a limit on every machine. Unfortunately
shared hosters are very limited.

robinbonnes <notifications@github.com> schrieb am Mi., 9. Nov. 2016, 23:29:

**Comment by daftspunk** [comment]
@jBOKA please proceed with the following

1. Make EXIF optional, like sharpen (for consistency)
1. Default EXIF setting to `TRUE` (for expectation)
1. Perform a memory check that disables memory intensive features at some reasonable level

It is OK to make it fail silently for now, we will need to consider adding some advice somewhere to convey the limitation, whatever it ends up being. eg:

> Minimum requirements for image sharpening and EXIF rotation is [XXX]MB

**Comment by tschallacka** [comment]
Uhm, if the problem is caused by loss of exif data, why not rewrite the exif on the thumb data to skip the uncompressed jpg hogging up the memory.

 https://github.com/lsolesen/pel

Just an idea, but might be more usuable solution than the current one.

**Comment by jBOKA** [comment]
It is not. The problem is caused by memory restrictions for example on
shared hosting.
You can consider that and skip. I was just pretty busy and didn't finish
the whole thing. But apart from memory everything's working fine

Tschallacka <notifications@github.com> schrieb am Do., 2. März 2017, 13:01:

**Comment by LukeTowers** [comment]
With the recent change to bump down the default quality from 95 to 90, has the memory usage improved?
