### ISSUE TITLE
Richeditor choose link not working properly 

### ISSUE THREAD

**Issue by anand-patel** [octobercms/october#3064]
Hi, in richeditor choose link function not working properly, it always add link at the start of the content if we add link from choose link(select page dropdown)

##### Expected behavior
- Go the static page
- Type text as link name in richeditor(after any content not at the start)
- Select that text
- Click on insert link from toolbar
- It will open form with URL and Text(text field is auto populated from the selected text)
- Click on search icon(choose link)
- It will open page selection dropdown 
- Select static page or CMS page
- It open form with URL and text
- Text field should be selected text if user has selected text, or it should be page name
- Affter clicking on insert, it should insert link where we have selected text or a cursor points.

##### Actual behavior
- Go the static page
- Type text as link name in richeditor(after any content not at the start)
- Select that text
- Click on insert link from toolbar
- It will open form with URL and Text(text field is auto populated from the selected text)
- Click on search icon(choose link)
- It will open page selection dropdown 
- Select static page or CMS page
- It will again open form with URL and Text 
- Text field is changed with the Page name
- When we click on insert, it alwasy add at the start of that content, not where we selected that text or a cursor

##### October build
419

**Comment by joltmode** [comment]
Was about to report the same issue. Will just add my notes here. First off, I made a GIF:

![OctoberCMS Froala Link Bug](https://media.giphy.com/media/26n7b43HLKcr2fOJa/giphy.gif)

There are actually multiple issues I have noticed there, therefore I added numbers and highlights to the GIF:

1. The label is supposed to be hidden(?), but there's something wrong with the technique over there, that also obscures the input field. This also happens for Image/Video/Audio insertion popups.  
![Label obscures input field](https://user-images.githubusercontent.com/1030080/29872450-5b092116-8d98-11e7-9399-3385572c6d37.png)  
The element highlight in web view shows the overlap.
2. The URL field is not populated at all. I, at least, expect it to show the URL of the selected page.
3. The Text field is unexpectedly updated, even though, I had selected a text to be linked before insertion. I expect it to be left at the selected value.
4. Well, after inserting the link, you can see how it's prepended to the content, not updated in place of selected text.

Didn't notice this while recording the GIF — the href for the freshly inserted link is actually left empty (probably that's why it didn't show the URL for `#2`). As seen in code view:  
![image](https://user-images.githubusercontent.com/1030080/29876052-65350ee6-8da4-11e7-9309-08248094c08b.png)

---

There are also problems when editing links.  
Don't know if it should be in a different issue or not - they seem really related and possibly reside in the same codebase.

See this (immediately after inserting a link with the buggy behavior above):

![OctoberCMS Froala Link Edit Bug](https://media.giphy.com/media/3ohhwr0E1ufxX3STOE/giphy.gif)

I select to edit the freshly inserted/buggy link and change it's target page to another. First thing that we see is that the URL is empty - well, obvious, since it wasn't set before. Though, this time, after page selection the URL gets updated, but updating the link, doesn't actually update, but insert a new link again prepended to the content.

The good news here are that when I open the freshly added "AJAX Framework" link for editing, the label doesn't obscure the input.

---

An interesting quirk is this one. After inserting the buggy link, switch to code view and back. That seems to fix the issue with editing the link. Though, introduces a new one - inserting any new link, will replace the one at the start... as if some references were left intact or something.  
![OctoberCMS Froala Link Edit Bug after changing to Code View](https://media.giphy.com/media/3ohhwLBXjunN9I9G12/giphy.gif)

I also made another test to see if drag selection affected any of this... and, no, not the case. Switching to code and back, then by any means editing the link will edit it in place, but new link insertions will actually edit our unfortunate link.

P.S. I made yet another test, adding the link, switching to code and back and inserting without attempt to edit the buggy link. It also resulted in the buggy link getting edited.

---

None of this happens, if I input the URL by hand.

---

P.S. A sidenote to `#1` (since it actually isn't related to the page thing) - starting to type in the input seems to fix the layout.  
![OctoberCMS Froala Link Edit label obscurity](https://media.giphy.com/media/3ohhwsI3Gkld1JGQcE/giphy.gif)

---

If I'd play around with this link thing for a while, I'd probably catch some more stuff, but I feel it's pointless because it feels like quite a simple fix to one thing that would quickly check anything else - it all feels too related.

**Comment by LukeTowers** [comment]
@joltmode Excellent bug report! Thanks very much for digging into this! 
I'm assuming this is due to a bug in getting the position of the cursor when inserting the link, although the whole "not copying the URL" is a bit odd.

This may be related to https://github.com/froala/wysiwyg-editor/issues/635, would you be willing to look into that to see if you can find a fix for this?

Thanks again for your help!

**Comment by tim0991** [comment]
+1

**Comment by LukeTowers** [comment]
@tim0991 Adding "+1" to an issue is not helpful and will not increase the odds that it gets taken care of. Please contribute to resolving the issue by reviewing the relevant pull requests and providing feedback on whether they adequately solve the problem or not.

**Comment by LukeTowers** [comment]
Should be fixed in the latest build (452)

**Comment by Eoler** [comment]
The only thing that is currently (build 459) fixed is empty href attribute, selected text and insertion point are still buggy - tested in custom FormController's richtext field but behavior is same as in [first video here](3064#issuecomment-326008148).

**Comment by LukeTowers** [comment]
@Eoler please test it on the latest copy of the develop branch and create a new detailed issue if it still persists.

**Comment by Eoler** [comment]
> @Eoler please test it on the latest copy of the develop branch and create a new detailed issue if it still persists.

I tested it on v460 - it fails the same way as in first part of this message: https://github.com/octobercms/october/issues/3064#issuecomment-326008148
step-by-step (1. to 4.) including embedded screen capture.

**Comment by LukeTowers** [comment]
@Eoler could you make a new issue with a detailed description please?

**Comment by Eoler** [comment]
> @Eoler could you make a new issue with a detailed description please?

Sorry but I don't understand why - this is one of the best bug report in whole tracker (edited & annotated video included), what details are missing?

**Comment by bennothommo** [comment]
@Eoler your comment [here](https://github.com/octobercms/october/issues/3064#issuecomment-551109399) is suggesting a different issue to the initial issue that was posted, which is why @LukeTowers is asking for it to be registered as a different issue. It just helps us organise exactly which issues are still applicable in recent builds.

**Comment by Eoler** [comment]
> @Eoler your comment [here](https://github.com/octobercms/october/issues/3064#issuecomment-551109399) is suggesting a different issue to the initial issue that was posted

Its the same issue:
> it fails the same way as in first part of this message: [#3064 (comment)](https://github.com/octobercms/october/issues/3064#issuecomment-326008148)
> step-by-step (1. to 4.) including embedded screen capture.

**Comment by bennothommo** [comment]
@Eoler apologies, my mistake.

**Comment by Eoler** [comment]
> @Eoler apologies, my mistake.

No problem, guess I'm just bitter for Froala going the way of ExtJS/Delphi which probably leave us with non-maintaned RTE...
