### ISSUE TITLE
October composer install fails with missing ControllerServiceProvider

### ISSUE THREAD

**Issue by egerheed** [octobercms/october#3081]
Cloning repo and running composer install fails when running
`php artisan october:util set build`

Error message reads:

> [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Class 'Illuminate\Routing\ControllerServiceProvider' not found
> 
> Script php artisan october:util set build handling the post-update-cmd event returned with error code 1

This error means I cannot deploy locally, on vagrant or on forge, and not sure what the problem is.

##### October build
Build 419

**Comment by MihaiVlasceanu** [comment]
I am having the same issue. 
I am trying to upgrade from 419 to 420.

**Comment by daftspunk** [comment]
Make sure you update your composer.json file to ask for Laravel 5.5:
https://github.com/octobercms/october/blob/master/composer.json#L34

**Comment by MihaiVlasceanu** [comment]
This is my composer:


```
{
    "name": "october/october",
    "description": "October CMS",
    "homepage": "http://octobercms.com",
    "keywords": ["october", "cms", "octobercms", "laravel"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Co-founder"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Co-founder"
        }
    ],
    "support": {
        "issues": "https://github.com/octobercms/october/issues",
        "forum": "http://octobercms.com/forum/",
        "docs": "http://octobercms.com/docs/",
        "irc": "irc://irc.freenode.net/october",
        "source": "https://github.com/octobercms/october"
    },
    "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.5.*",
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~5.7",
        "phpunit/phpunit-selenium": "~1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}

```

**Comment by daftspunk** [comment]
```
Class 'Illuminate\Routing\ControllerServiceProvider' not found
```

This error is caused by using Laravel 5.1 vendor directory with Build 420 modules directory. Check to make sure the Laravel version in your vendor directory is in fact 5.5.

**Comment by mmvcode** [comment]
vendor\laravel\framework\src\Illuminate\Foundation\Application.php:
```
...
/**
     * The Laravel framework version.
     *
     * @var string
     */
    const VERSION = '5.5.1';
...
```

vendor\laravel\framework\composer.json:
```
...
"extra": {
        "branch-alias": {
            "dev-master": "5.5-dev"
        }
    },
...
```

**Comment by mmvcode** [comment]
Seems like the error only occurs (for me) only if following the composer installation.
I did a fresh install with:
`php -r "eval('?>'.file_get_contents('https://octobercms.com/api/installer'));"`

Then updated to build 420 and the error did not show up anymore.

**Comment by daftspunk** [comment]
Perhaps it could be the other way around, Build 419 modules with Laravel 5.5 vendor.

Does your provides file (modules/system/providers.php) look like this https://github.com/octobercms/october/blob/master/modules/system/providers.php?

**Comment by mmvcode** [comment]
Yes, they are the same.
That means that something went wrong when updating to 420 build, right?

**Comment by AugmentBLU** [comment]
I'm getting similar issues. I tried to update my composer, deleted the vendor and modules folders in case they needed to be.

```
Writing lock file
Generating autoload files
> php artisan october:util set build


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Illuminate\Routing\ControllerServiceProvider' not found


Script php artisan october:util set build handling the post-update-cmd event returned with error code 1
```

Fresh install works but the above error is from an existing project. Strange that it was a 420 dev build which worked and now it won't work using the master branch.

**Comment by AugmentBLU** [comment]
```
  - Installing october/rain (v1.0.421): Downloading (100%)
  - Installing october/system (v1.0.419): Downloading (100%)
  - Installing october/backend (v1.0.419): Downloading (100%)
  - Installing october/cms (v1.0.419): Downloading (100%)
```

Shouldn't they all reflect 421? The same issue still appearing for me.

```
> php artisan october:util set build

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Illuminate\Routing\ControllerServiceProvider' not found

Script php artisan october:util set build handling the post-update-cmd event returned with error code 1
```

**Comment by lsve** [comment]
+1
the same problem

**Comment by zzdb** [comment]
+1
Can't install it

**Comment by that0n3guy** [comment]
This error is because 419 is being installed for many of the modules.   If we would set specific of 420 in composer, it would say something like "octobercms setting version"  and it would download 419

The fix we found for this was to:

- enable edge updates in config.php
- add dev-develop for version: 
```
        "october/rain": "dev-develop",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
```

This sucks though as it forces us to do edge and dev-develop... which we do not want to do.

**Comment by AugmentBLU** [comment]
This still does not work. I've tried a fresh install using different combinations and it will not work, it's not related to plugins using 419.
If you use this in your composer

```
  "october/rain": "dev-develop",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
```

You get this error.

```
  Problem 1
    - Installation request for october/system dev-develop -> satisfiable by october/system[dev-develop].
    - october/system dev-develop requires october/rain dev-l55upgrade -> no matching package found.
  Problem 2
    - Installation request for october/backend dev-develop -> satisfiable by october/backend[dev-develop].
    - october/backend dev-develop requires october/rain dev-l55upgrade -> no matching package found.
  Problem 3
    - Installation request for october/cms dev-develop -> satisfiable by october/cms[dev-develop].
    - october/cms dev-develop requires october/rain dev-l55upgrade -> no matching package found.
```

**Comment by that0n3guy** [comment]
My method above worked for 420 (we got it working on friday).    If you look at packagist, 421 requires taht weird l55upgrade version https://packagist.org/packages/october/system#v1.0.421

While 420 requires dev-develop: https://packagist.org/packages/october/system#v1.0.420

And 419 only required `~1.0`: https://packagist.org/packages/october/system#v1.0.419

There is definately a requirements issue going on from one packate (system) to another (rain).

**Comment by that0n3guy** [comment]
If you set cms/system/backend to v1.0.420 and rain to dev-develop... I bet it will work.     Or if you set cms/system/backend to and rain to v1.0.421 it will work.    That said, I have no idea what is in the code of those dev-develop/dev-l55upgrade versions.

**Comment by AugmentBLU** [comment]
Using the following did get my dev area back up for now.

```
"october/rain": "dev-develop",
"october/system": "v1.0.420",
"october/backend": "v1.0.420",
"october/cms": "v1.0.420",
```

I tried to set the version manually to v1.0.421 before and got these errors. As you said, it requires the old upgrade dependencies. 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for october/system v1.0.421 -> satisfiable by october/system[v1.0.421].
    - october/system v1.0.421 requires october/rain dev-l55upgrade -> no matching package found.
  Problem 2
    - Installation request for october/backend v1.0.421 -> satisfiable by october/backend[v1.0.421].
    - october/backend v1.0.421 requires october/rain dev-l55upgrade -> no matching package found.
  Problem 3
    - Installation request for october/cms v1.0.421 -> satisfiable by october/cms[v1.0.421].
    - october/cms v1.0.421 requires october/rain dev-l55upgrade -> no matching package found.
```

**Comment by LukeTowers** [comment]
Fixed the issue, but it won't be properly reflected in Composer until a new build is pushed. I'll leave that up to @daftspunk if he wants to bump the version, otherwise you can manually apply the changes from https://github.com/octobercms/october/commit/8a8013e52e94a30ef14435cf63f796bedb28b117 and then everything should work

**Comment by AugmentBLU** [comment]
When trying to start a new project, it downloads 421 as expected. It moves on to downloading dependencies etc and then overwrites the 421 build with 419. Here's the log of my git bash test install. Might help with resolving the issue. 

```
$ composer create-project october/october
Installing october/october (v1.0.421)
- Installing october/october (v1.0.421): Downloading (100%)
Created project in X:\development\projects\gm\421\october
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 81 installs, 0 updates, 0 removals
- Installing wikimedia/composer-merge-plugin (dev-master 0e7f98d): DownloadingDownloading (100%)
- Installing composer/installers (v1.4.0): Downloading (100%)
- Installing linkorb/jsmin-php (1.0.0): Downloading (100%)
- Installing symfony/polyfill-mbstring (v1.5.0): Downloading (100%)
- Installing twig/twig (v2.4.3): Downloading (100%)
- Installing symfony/yaml (v3.3.8): Downloading (100%)
- Installing oyejorge/less.php (v1.7.0.14): Downloading (100%)
- Installing league/csv (8.2.2): Downloading (100%)
- Installing leafo/scssphp (v0.6.7): Downloading (100%)
- Installing symfony/var-dumper (v3.3.8): Downloading (100%)
- Installing jakub-onderka/php-console-color (0.1): Downloading (connecting...Downloading (100%)
- Installing jakub-onderka/php-console-highlighter (v0.3.2): Downloading (connDownloading (100%)
- Installing dnoegel/php-xdg-base-dir (0.1): Downloading (100%)
- Installing nikic/php-parser (v3.1.1): Downloading (100%)
- Installing psr/log (1.0.2): Downloading (100%)
- Installing symfony/debug (v3.3.8): Downloading (100%)
- Installing symfony/console (v3.3.8): Downloading (100%)
- Installing psy/psysh (v0.8.11): Downloading (100%)
- Installing vlucas/phpdotenv (v2.4.0): Downloading (100%)
- Installing symfony/css-selector (v3.3.8): Downloading (100%)
- Installing tijsverkoyen/css-to-inline-styles (2.2.0): Downloading (connectinDownloading (100%)
- Installing symfony/routing (v3.3.8): Downloading (100%)
- Installing symfony/process (v3.3.8): Downloading (100%)
- Installing symfony/http-foundation (v3.3.8): Downloading (100%)
- Installing symfony/event-dispatcher (v3.3.8): Downloading (100%)
- Installing symfony/http-kernel (v3.3.8): Downloading (100%)
- Installing symfony/finder (v3.3.8): Downloading (100%)
- Installing doctrine/lexer (v1.0.1): Downloading (100%)
- Installing egulias/email-validator (2.1.2): Downloading (100%)
- Installing swiftmailer/swiftmailer (v6.0.1): Downloading (100%)
- Installing paragonie/random_compat (v2.0.10): Downloading (100%)
- Installing ramsey/uuid (3.7.0): Downloading (100%)
- Installing psr/simple-cache (1.0.0): Downloading (100%)
- Installing psr/container (1.0.0): Downloading (100%)
- Installing symfony/translation (v3.3.8): Downloading (100%)
- Installing nesbot/carbon (1.22.1): Downloading (100%)
- Installing mtdowling/cron-expression (v1.2.0): Downloading (100%)
- Installing monolog/monolog (1.23.0): Downloading (100%)
- Installing league/flysystem (1.0.41): Downloading (100%)
- Installing erusev/parsedown (1.6.3): Downloading (100%)
- Installing doctrine/inflector (v1.2.0): Downloading (100%)
- Installing laravel/framework (v5.5.2): Downloading (100%)
- Installing laravel/tinker (v1.0.2): Downloading (100%)
- Installing kriswallsmith/assetic (v1.4.0): Downloading (100%)
- Installing jenssegers/date (v3.2.12): Downloading (100%)
- Installing erusev/parsedown-extra (0.7.1): Downloading (100%)
- Installing doctrine/collections (v1.5.0): Downloading (100%)
- Installing doctrine/cache (v1.7.1): Downloading (100%)
- Installing doctrine/annotations (v1.5.0): Downloading (100%)
- Installing doctrine/common (v2.7.3): Downloading (100%)
- Installing doctrine/dbal (v2.5.13): Downloading (100%)
- Installing october/rain (v1.0.421): Downloading (100%)
- Installing october/system (v1.0.419): Downloading (100%)
- Installing october/backend (v1.0.419): Downloading (100%)
- Installing october/cms (v1.0.419): Downloading (100%)
- Installing fzaninotto/faker (v1.7.1): Downloading (100%)
- Installing sebastian/recursion-context (2.0.0): Downloading (100%)
- Installing sebastian/exporter (2.0.0): Downloading (100%)
- Installing sebastian/diff (1.4.3): Downloading (100%)
- Installing sebastian/comparator (1.2.4): Downloading (100%)
- Installing sebastian/version (2.0.1): Downloading (100%)
- Installing sebastian/resource-operations (1.0.0): Downloading (connecting...Downloading (100%)
- Installing doctrine/instantiator (1.1.0): Downloading (100%)
- Installing phpunit/php-text-template (1.2.1): Downloading (100%)
- Installing phpunit/php-timer (1.0.9): Downloading (100%)
- Installing phpunit/php-file-iterator (1.4.2): Downloading (100%)
- Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (connectiDownloading (100%)
- Installing phpunit/php-token-stream (2.0.1): Downloading (100%)
- Installing webmozart/assert (1.2.0): Downloading (100%)
- Installing phpdocumentor/reflection-common (1.0): Downloading (connecting...Downloading (100%)
- Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
- Installing phpdocumentor/reflection-docblock (4.1.1): Downloading (connectinDownloading (100%)
- Installing phpspec/prophecy (v1.7.2): Downloading (100%)
- Installing myclabs/deep-copy (1.6.1): Downloading (100%)
- Installing sebastian/global-state (1.1.1): Downloading (100%)
- Installing sebastian/environment (2.0.0): Downloading (100%)
- Installing sebastian/object-enumerator (2.0.1): Downloading (100%)
- Installing phpunit/phpunit-mock-objects (3.4.4): Downloading (connecting...)Downloading (100%)
- Installing phpunit/php-code-coverage (4.0.8): Downloading (100%)
- Installing phpunit/phpunit (5.7.21): Downloading (100%)
- Installing phpunit/phpunit-selenium (1.4.1): Downloading (100%)
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/console suggests installing symfony/filesystem ()
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
egulias/email-validator suggests installing ext-intl (PHP Internationalization Libraries are required to use the SpoofChecking validation)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/translation suggests installing symfony/config ()
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~3.3).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (~1.0).)
kriswallsmith/assetic suggests installing leafo/lessphp (Assetic provides the integration with the lessphp LESS compiler)
kriswallsmith/assetic suggests installing ptachoire/cssembed (Assetic provides the integration with phpcssembed to embed data uris)
kriswallsmith/assetic suggests installing leafo/scssphp-compass (Assetic provides the integration with the SCSS compass plugin)
kriswallsmith/assetic suggests installing patchwork/jsqueeze (Assetic provides the integration with the JSqueeze JavaScript compressor)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating autoload files
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files
> php artisan october:util set build


[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Illuminate\Routing\ControllerServiceProvider' not found


Script php artisan october:util set build handling the post-update-cmd event returned with error code 1
```

**Comment by mmvcode** [comment]
This is not fixed.
Having the same issue as @AugmentBLU

The suggestion in [this comment](https://github.com/octobercms/october/issues/3081#issuecomment-327011765) does fix it.

**Comment by daftspunk** [comment]
Yup, we are working on it. The issues was closed automatically by a commit.

**Comment by daftspunk** [comment]
Reports coming in that it should be fixed now.
