### ISSUE TITLE
Fresh install: Class 'Backend\Widgets\MediaManager' not found

### ISSUE THREAD

**Issue by Blinks44** [octobercms/october#3185]
Greetings! 
After fresh install october via composer i have this error with mediamanager. I can reach dashboard if i comment error code, but media manager doesn't work. Any help?
![2017-10-20_00-13-45](https://user-images.githubusercontent.com/8570193/31794744-0491c480-b52c-11e7-9274-c5d7f632b502.png)

**Comment by LukeTowers** [comment]
How exactly did you install via composer? The class exists: https://github.com/octobercms/october/blob/develop/modules/backend/widgets/MediaManager.php

**Comment by Blinks44** [comment]
1) composer create-project october/october
2) 'disableCoreUpdates' => true,
3) php artisan october:install

Very strange, with composer i don't have those files.
![2017-10-20_00-35-00](https://user-images.githubusercontent.com/8570193/31795477-9671bcf0-b52e-11e7-8668-870a7520b714.png)

**Comment by LukeTowers** [comment]
Could you post your composer.json?

**Comment by LukeTowers** [comment]
You shouldn't have the new version of `Backend\Classes\Controller` if you don't have the new version of `Backend\Widgets\MediaFinder`

**Comment by Blinks44** [comment]
`{
    "name": "october/october",
    "description": "October CMS",
    "homepage": "http://octobercms.com",
    "keywords": ["october", "cms", "octobercms", "laravel"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Co-founder"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Co-founder"
        }
    ],
    "support": {
        "issues": "https://github.com/octobercms/october/issues",
        "forum": "http://octobercms.com/forum/",
        "docs": "http://octobercms.com/docs/",
        "irc": "irc://irc.freenode.net/october",
        "source": "https://github.com/octobercms/october"
    },
    "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.5.*",
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.7",
        "phpunit/phpunit": "~5.7",
        "phpunit/phpunit-selenium": "~1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}
`

**Comment by LukeTowers** [comment]
hmm. Very odd indeed. Could you try doing those steps again one by one and see if just the first step of creating the project with composer causes the error to occur?

**Comment by Blinks44** [comment]
Yep, same result... I have to run "php artisan october:install", because /backend show database error, but after that command the same error is showing

**Comment by Blinks44** [comment]
Folders structure in modules/backend/widgets/ and modules/cms/widgets/ are not the same as in your link and after composer...

**Comment by LukeTowers** [comment]
Does the folder structure change after running october:install?

**Comment by Blinks44** [comment]
Nope, this "different" folder structure is after composer clean install

**Comment by LukeTowers** [comment]
That is very bizarre indeed. The octoberrain/backend package doesn't have the new stuff yet
https://github.com/octoberrain/backend/blob/master/classes/Controller.php#L156.

Can you try clearing your composer cache and installing again?

**Comment by Blinks44** [comment]
Done. Same folders structure, different error. No MediaManager.php and mediamanager folder in backend/widgets
![2017-10-20_01-17-13](https://user-images.githubusercontent.com/8570193/31796954-7a546c4c-b534-11e7-8205-2f3ddde8df6a.png)

**Comment by LukeTowers** [comment]
Wtf. Could you change your october/backend to load from dev-develop and see if that changes anything?

**Comment by Blinks44** [comment]
Again i did clear composer cache, install october, composer update, php artisan october:install and now there is no error, buuut... Very odd behaviour...
![2017-10-20_01-31-22](https://user-images.githubusercontent.com/8570193/31797416-cdaf5e18-b536-11e7-8041-f6efffabd10a.png)

**Comment by Blinks44** [comment]
And now after october:update, everything is working. I am confused...

**Comment by LukeTowers** [comment]
October:update downloads the build files from the server, it's as if you installed via the installer instead. So I can see how that would solve the problem. I have no idea what is so broken about your composer instance though...

**Comment by Blinks44** [comment]
Ok, thank you for your help, i will try to dig dipper in composer installation, but for now it is working...

**Comment by Blinks44** [comment]
Ok, today i came to work and tried to install october through composer on my work machine. Nothing works...
1) composer clearcache
2) composer create-project october
3) october:install
4) composer update
5) october:update
and Class 'Backend\Widgets\MediaManager' not found...
I don't know what to do, really, why composer doesn't install all files

**Comment by Blinks44** [comment]
With curl installation folders structure is the same as composer installation, but everything works fine, without any errors.
This screenshot after curl installation:
![2017-10-20_11-54-22](https://user-images.githubusercontent.com/8570193/31813041-97d667bc-b58d-11e7-9740-4fc64839a3bd.png)

**Comment by LukeTowers** [comment]
Curl installation would download a stored Build 419 version. 

Composer should in theory download a copy of the latest build (426), however it seems to be downloading a zombie version combining a couple of different builds. I haven't tried to replicate this myself yet.

**Comment by JumpLink** [comment]
Any Solution? I get this error in all the ways for an update, cli, composer and over the backend.

**Comment by LukeTowers** [comment]
@Blinks44 the build process hasn't been running correctly since Build 422, we believe we've fixed the issue. Could you try another fresh install using composer and see if it's fixed for you now?

**Comment by Blinks44** [comment]
@LukeTowers Yep, now everything is fine!

**Comment by chrisbethelepb** [comment]
@LukeTowers I ran in to the same problem, but I did `artisan october:update` first. Deleting the `vendor` directory and re-running `composer install` does not fix it either. Same error. After running `composer dump-autoload` it still cannot find `System\Twig\MediaLibrary`.

PHP 7.1
Composer 1.5.2
macOS Sierra and RHEL 7.5 have the same problem

It's acting like the `modules/system/composer.json` isn't being read for the `System\Classes` namespace.

A clean install appeared to work, but my existing site does not.

**Comment by chrisbethelepb** [comment]
Ah, just read through @JumpLink's suggestion (https://github.com/octobercms/october/issues/3189#issuecomment-338499920) and changing `modules/system/twig/Extension.php` did fix the problem. The issue for me is that I have Jenkins building (and it does a composer install) and reinstalls the bad class name every build. Any idea when that fix will be pushed out?

**Comment by LukeTowers** [comment]
@chrisbethelepb could I see your composer.json file?

**Comment by chrisbethelepb** [comment]
```json
{
    "name": "october/october",
    "description": "October CMS",
    "homepage": "http://octobercms.com",
    "keywords": ["october", "cms", "octobercms", "laravel"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Co-founder"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Co-founder"
        }
    ],
    "support": {
        "issues": "https://github.com/octobercms/october/issues",
        "forum": "http://octobercms.com/forum/",
        "docs": "http://octobercms.com/docs/",
        "irc": "irc://irc.freenode.net/october",
        "source": "https://github.com/octobercms/october"
    },
    "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.5.*",
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~5.7",
        "phpunit/phpunit-selenium": "~1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}

```

**Comment by chrisbethelepb** [comment]
@LukeTowers if you `rm -rf vendor && composer install` it re-breaks the `modules/system/twig/Extension.php` file back to:

`use System\Classes\MediaLibary;`

**Comment by chrisbethelepb** [comment]
@LukeTowers here's a snippet of my composer.json file showing the versions I'm getting:

```json
        {
            "name": "october/backend",
            "version": "v1.0.426",
            "source": {
                "type": "git",
                "url": "https://github.com/octoberrain/backend.git",
                "reference": "7511d4e57833d1d1876c9ace7f30522ec74c44db"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/octoberrain/backend/zipball/7511d4e57833d1d1876c9ace7f30522ec74c44db",
                "reference": "7511d4e57833d1d1876c9ace7f30522ec74c44db",
                "shasum": ""
            },
            "require": {
                "composer/installers": "~1.0",
                "october/rain": "~1.0",
                "php": ">=7.0"
            },
            "type": "october-module",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Backend\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Alexey Bobkov",
                    "email": "aleksey.bobkov@gmail.com"
                },
                {
                    "name": "Samuel Georges",
                    "email": "daftspunky@gmail.com"
                }
            ],
            "description": "Backend module for October CMS",
            "homepage": "http://octobercms.com",
            "keywords": [
                "backend",
                "october",
                "october cms"
            ],
            "time": "2017-10-16T06:56:34+00:00"
        },
        {
            "name": "october/cms",
            "version": "v1.0.426",
            "source": {
                "type": "git",
                "url": "https://github.com/octoberrain/cms.git",
                "reference": "94a0d4301e2e6730c6d1cb3770892fa30b14579a"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/octoberrain/cms/zipball/94a0d4301e2e6730c6d1cb3770892fa30b14579a",
                "reference": "94a0d4301e2e6730c6d1cb3770892fa30b14579a",
                "shasum": ""
            },
            "require": {
                "composer/installers": "~1.0",
                "october/rain": "~1.0",
                "php": ">=7.0"
            },
            "type": "october-module",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Cms\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Alexey Bobkov",
                    "email": "aleksey.bobkov@gmail.com"
                },
                {
                    "name": "Samuel Georges",
                    "email": "daftspunky@gmail.com"
                }
            ],
            "description": "CMS module for October CMS",
            "homepage": "http://octobercms.com",
            "keywords": [
                "cms",
                "october",
                "october cms"
            ],
            "time": "2017-10-14T14:31:04+00:00"
        },
        {
            "name": "october/rain",
            "version": "v1.0.426",
            "source": {
                "type": "git",
                "url": "https://github.com/octobercms/library.git",
                "reference": "768aa77cf4ad016a93281a2d5b080b9aeb2e2185"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/octobercms/library/zipball/768aa77cf4ad016a93281a2d5b080b9aeb2e2185",
                "reference": "768aa77cf4ad016a93281a2d5b080b9aeb2e2185",
                "shasum": ""
            },
            "require": {
                "doctrine/dbal": "2.5.*",
                "erusev/parsedown-extra": "~0.7",
                "jenssegers/date": "~3.0",
                "kriswallsmith/assetic": "~1.3",
                "laravel/tinker": "~1.0",
                "leafo/scssphp": "~0.6",
                "league/csv": "~8.0",
                "linkorb/jsmin-php": "~1.0",
                "oyejorge/less.php": "~1.7",
                "php": ">=7.0",
                "symfony/yaml": "~3.2",
                "twig/twig": "~2.0"
            },
            "replace": {
                "october/auth": "self.version",
                "october/config": "self.version",
                "october/database": "self.version",
                "october/extension": "self.version",
                "october/filesystem": "self.version",
                "october/halcyon": "self.version",
                "october/html": "self.version",
                "october/mail": "self.version",
                "october/network": "self.version",
                "october/parse": "self.version",
                "october/router": "self.version",
                "october/support": "self.version",
                "october/translation": "self.version"
            },
            "require-dev": {
                "illuminate/database": "5.5.*",
                "illuminate/events": "5.5.*",
                "illuminate/filesystem": "5.5.*",
                "illuminate/log": "5.5.*",
                "illuminate/mail": "5.5.*",
                "illuminate/pagination": "5.5.*",
                "illuminate/queue": "5.5.*",
                "illuminate/routing": "5.5.*",
                "illuminate/support": "5.5.*",
                "illuminate/validation": "5.5.*",
                "illuminate/view": "5.5.*",
                "phpunit/phpunit": "~5.7",
                "swiftmailer/swiftmailer": "~5.1",
                "symfony/config": "2.7.*",
                "symfony/css-selector": "~3.1",
                "symfony/dom-crawler": "~3.1"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0-dev"
                }
            },
            "autoload": {
                "files": [
                    "src/Support/helpers.php",
                    "src/Html/helpers.php"
                ],
                "psr-4": {
                    "October\\Rain\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Alexey Bobkov",
                    "email": "aleksey.bobkov@gmail.com"
                },
                {
                    "name": "Samuel Georges",
                    "email": "daftspunky@gmail.com"
                }
            ],
            "description": "October Rain Library",
            "homepage": "http://octobercms.com",
            "keywords": [
                "cms",
                "october",
                "rain"
            ],
            "time": "2017-10-13T23:10:00+00:00"
        },
        {
            "name": "october/system",
            "version": "v1.0.426",
            "source": {
                "type": "git",
                "url": "https://github.com/octoberrain/system.git",
                "reference": "281a48a55805804f7be03c06b8ddb94df0bb8ceb"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/octoberrain/system/zipball/281a48a55805804f7be03c06b8ddb94df0bb8ceb",
                "reference": "281a48a55805804f7be03c06b8ddb94df0bb8ceb",
                "shasum": ""
            },
            "require": {
                "composer/installers": "~1.0",
                "october/rain": "~1.0",
                "php": ">=7.0"
            },
            "type": "october-module",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "System\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Alexey Bobkov",
                    "email": "aleksey.bobkov@gmail.com"
                },
                {
                    "name": "Samuel Georges",
                    "email": "daftspunky@gmail.com"
                }
            ],
            "description": "System module for October CMS",
            "homepage": "http://octobercms.com",
            "keywords": [
                "october",
                "october cms",
                "system"
            ],
            "time": "2017-10-16T06:56:34+00:00"
        },
```

**Comment by LukeTowers** [comment]
Well build 426 is one commit behind the fix, so until build 427 drops, you can tell composer to use the develop branches instead:
```
"october/rain": "dev-develop as 1.0",
"october/system": "dev-develop",
"october/backend": "dev-develop",
"october/cms": "dev-develop",
```
@chrisbethelepb

**Comment by chrisbethelepb** [comment]
@LukeTowers I noticed today that 427 was released here: https://octobercms.com/changelog

I reverted my composer.json back to the standard branches, but the issue is still there. It looks like only `october/rain` was updated to v1.0.427. Here's the versions updated by composer:

```
  - Updating laravel/framework (v5.5.19 => v5.5.20): Loading from cache
  - Updating october/rain (dev-develop => v1.0.427): Downloading (100%)         
  - Updating october/system (dev-develop => v1.0.426): Loading from cache
  - Updating october/backend (dev-develop => v1.0.426): Loading from cache
  - Updating october/cms (dev-develop => v1.0.426): Loading from cache

```

**Comment by LukeTowers** [comment]
I'll ping @daftspunk, it seems like the cron job for doing the split to the readonly repos for the build process hasn't been working correctly

**Comment by chrisbethelepb** [comment]
@LukeTowers the 428 build released resolves the issue for me. Thanks! 👍
