### ISSUE TITLE
Incorrect default View.php config causes open_basedir error

### ISSUE THREAD

**Issue by vevers** [octobercms/october#3473]
##### Expected behavior
A clean OctoberCMS installation should work without any problems.

##### Actual behavior
A new clean installation errors out with an open_basedir error (is_dir(): open_basedir restriction in effect).

##### Cause
/config/view.php contains the following default view paths:
```
    'paths' => [
        realpath(base_path('resources/views'))
    ],
```
The "/resources/views" folder doesn't exist by default though in an OctoberCMS project .
This causes realpath() to return FALSE (see [PHP Documentation](http://php.net/manual/en/function.realpath.php)), which causes the default config to basically end up like this:

```
    'paths' => [
        FALSE
    ],
```
The view paths are loaded by the Laravel Framework in /vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php within the loadViewsFrom() method.

>     protected function loadViewsFrom($path, $namespace)
>     {
>         if (is_array($this->app->config['view']['paths'])) {
>             foreach ($this->app->config['view']['paths'] as $viewPath) {
>                 if (is_dir($appPath = $viewPath.'/vendor/'.$namespace)) {
>                     $this->app['view']->addNamespace($namespace, $appPath);
>                 }
>             }
>         }
> 
>         $this->app['view']->addNamespace($namespace, $path);
>     }

Because the $this->app->config['view']['paths'] array now only contains one path with the value FALSE, $viewPath will be ignored, causing is_dir trying to determine if "[serverroot]/vendor/".$namespace is a valid path. When open_basedir protection is enabled, this causes is_dir to crash, because it tries to read from a non-allowed location.

##### Possible Solutions

1. Remove "_realpath(base_path('resources/views'))_" from the default _config/view.php_ file

or 

2. Replace realpath() with a better function that doesn't return false for non-existing folders

or

3. (Add a default empty "/resources/views" folder to the OctoberCMS project)

##### October build
434

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/9277b771e0326183ff3655816f2581e0cfcd1f65 and https://github.com/octobercms/october/commit/b5009fde112befa970cebc3f270671eb22c462f8

**Comment by hlev** [comment]
Not meaning to resurrect a 4 yrs old issue thread, but just removing the default Laravel blade templates from the `$config['view']['paths']` array alone did not fix the issue for an older October installation.

October 1.0 (uses Laravel 5.5) was being migrated from a PHP 7.1 hosting environment to PHP 7.4. The `open_basedir` restriction must have been stricter in the latter.

For any poor soul that wanders around here with this issue, here's what I did:

1. Removed the default view storage path from `view.php`
```
    //open_basedir issues
    //https://github.com/octobercms/october/issues/3473
    //https://github.com/octobercms/october/commit/9277b771e0326183ff3655816f2581e0cfcd1f65
    'paths' => [
        //realpath(base_path('resources/views'))
    ],
```
2. This alone was insufficient, something else also were populating the array with a `false` value. So as a quick fix instead of hunting that down, I changed `Illuminate\Support\ServiceProvider` in place and added a `!is_bool($viewPath)` check, since we're expecting a string anyway.
```
    protected function loadViewsFrom($path, $namespace)
    {
        if (is_array($this->app->config['view']['paths'])) {
            foreach ($this->app->config['view']['paths'] as $viewPath) {
                // if (is_dir($appPath = $viewPath.'/vendor/'.$namespace)) {
                if (!is_bool($viewPath) && is_dir($appPath = $viewPath.'/vendor/'.$namespace)) {
                    $this->app['view']->addNamespace($namespace, $appPath);
                }
            }
        }

        $this->app['view']->addNamespace($namespace, $path);
    }
```
Hopefully, in case of an upgrade, this will get replaced with something that prevents this issue already. Until then it buys me time to find the culprit.

**Comment by daftspunk** [comment]
Thanks, I couldn't reproduce it in v2.1.31 with `openbasedir` enabled. It would be interesting to know what was adding the `false` value for you.
