### ISSUE TITLE
UI issues on Firefox

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#4819]
OctoberCMS: 460 (and 459, 458, ...)
Firefox: 71 (and 70, 69, ...)

1. There is a dotted border around the tab title. **FIXED**
![issue1](https://user-images.githubusercontent.com/2959112/70525582-fda07200-1b47-11ea-9b70-e9025fead2ce.JPG)

2. There is a dotted border around the menu, when it is active. **FIXED**
![issue2](https://user-images.githubusercontent.com/2959112/70525588-02652600-1b48-11ea-94b9-87176525667e.JPG)

3. There are two scroll bars, when the page content is long.
![issue3](https://user-images.githubusercontent.com/2959112/70525598-0729da00-1b48-11ea-9eac-fe95ef098e22.JPG)

4. There is an ugly default tooltip, when I move the cursor above the tab or menu title. **FIXED**
![issue4](https://user-images.githubusercontent.com/2959112/70525607-0abd6100-1b48-11ea-8196-e2661b29205c.jpg)
and
![issue5](https://user-images.githubusercontent.com/2959112/70525616-0ee97e80-1b48-11ea-8a46-37f5c3f963cd.jpg)

5. The arrow of source editor bounces, when I move the cursor above it.
![issue6](https://user-images.githubusercontent.com/2959112/70525748-4d7f3900-1b48-11ea-90b7-c34227c7dcb5.JPG)

**Comment by ayumi-cloud** [comment]
I fixed points 1 and 2 and the pr's were merged, I just checked and now all the work I have done is not merged? 

See here part of the work:

https://github.com/octobercms/october/blob/0666e959e6f97ed9a22a33904c4a4cc2affd9fa3/modules/system/assets/ui/vendor/focus-visible/focus-visible.js

https://github.com/octobercms/october/blob/0666e959e6f97ed9a22a33904c4a4cc2affd9fa3/modules/backend/assets/less/layout/mainmenu.less#L14-L31

**Comment by ayumi-cloud** [comment]
I fixed points 1 and 2 and the pr's were merged, I just checked and now all the work I have done is not merged? 

See here part of the work:

https://github.com/octobercms/october/blob/0666e959e6f97ed9a22a33904c4a4cc2affd9fa3/modules/system/assets/ui/vendor/focus-visible/focus-visible.js

and

https://github.com/octobercms/october/blob/0666e959e6f97ed9a22a33904c4a4cc2affd9fa3/modules/backend/assets/less/layout/mainmenu.less#L14-L31

...and then there were more commits after that by me and Luke ?

**Comment by gergo85** [comment]
Pin

**Comment by LukeTowers** [comment]
@ayumi-cloud you might have to resubmit your PR to fix that again.

@gergo85 number 4 has been fixed by #4876

**Comment by ayumi-cloud** [comment]
@LukeTowers @gergo85 

I fixed issues 1 and 2, pr found here: https://github.com/octobercms/october/pull/4895

**Comment by gergo85** [comment]
The 3 and 5 issues have still not been fixed.

**Comment by gergo85** [comment]
The dotted border still appear.
![issue](https://user-images.githubusercontent.com/2959112/75758259-17f77f80-5d34-11ea-9446-3a5635446b31.PNG)

**Comment by LukeTowers** [comment]
@daftspunk see https://github.com/octobercms/october/pull/4895 & https://github.com/octobercms/october/pull/4965. Your call what you want to do with the focus styles. I've heard a number of complaints about the recent change in #4895 so reverting that and revisiting the original issue is probably the best course of action.
