### ISSUE TITLE
core resize filter don't use storage.resized.path to generate url

### ISSUE THREAD

**Issue by everyx** [octobercms/october#5412]
- OctoberCMS Build: v1.1.1
- PHP Version: php7.4
- Database Engine: MySQL 8
- Plugins Installed: 
Ompmega.MixHelper,
Martin.Forms,
Mohsin.txt,
VojtaSvoboda.TwigExtensions,
October.Drivers
Zaxbux.DOStorageDriver

### Description:
I use Zaxbux.DOStorageDriver plugin to connect OctoberCMS to user digitalocean space service, `uploads` and  `media` already get works, but `resize` also use my origin digitalocean endpoint `xxxx.digitaloceanspaces.com`

the template:
```twig
<img src="{{ item.images[0].image | media | resize(320, 320,{ mode: 'crop', quality: '100'}) }}" alt="{{ item.images[0].caption }}">
```

cms.php
```php
    'storage' => [

        'uploads' => [
            'disk'            => env('FILESYSTEM_DEFAULT', 'local'),
            'folder'          => env('FILESYSTEM_ROOT', '') . 'uploads',
            'path'            => env('FILESYSTEM_ROOT_URL', '/storage/app/') . 'uploads',
            'temporaryUrlTTL' => 3600,
        ],

        'media' => [
            'disk'   => env('FILESYSTEM_DEFAULT', 'local'),
            'folder' => env('FILESYSTEM_ROOT', '') . 'media',
            'path'   => env('FILESYSTEM_ROOT_URL', '/storage/app/') . 'media',
        ],

        'resized' => [
            'disk'   => env('FILESYSTEM_DEFAULT', 'local'),
            'folder' => env('FILESYSTEM_ROOT', '') . 'resized',
            'path'   => env('FILESYSTEM_ROOT_URL', '/storage/app/') . 'resized',
        ],

    ],
```

filesystem.php
```php
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
            'url'    => '/storage/app',
        ],

        'digitalocean' => [
            'driver' => 'do_spaces',
            'key'    => env('FILESYSTEM_DO_KEY', 'your-key'),
            'secret' => env('FILESYSTEM_DO_SECRET', 'your-secret'),
            'region' => env('FILESYSTEM_DO_REGION', 'your-region'),
            'space'  => env('FILESYSTEM_DO_SPACE', 'your-space'),
        ],

    ],
```

**Comment by LukeTowers** [comment]
This should be fixed by https://github.com/octobercms/october/pull/5379, will be included in v1.1.2

**Comment by everyx** [comment]
> This should be fixed by #5379, will be included in v1.1.2

@LukeTowers  I have manually applied #5379 , but it doesn't work, and move to s3 disk, this problem still exist.

**Comment by LukeTowers** [comment]
> resize also use my origin digitalocean endpoint xxxx.digitaloceanspaces.com

Please explain your original issue in more detail, it looks like you're using the same filesystem config for all three storage folders, in which case your described behaviour would be expected.

**Comment by everyx** [comment]
> > resize also use my origin digitalocean endpoint xxxx.digitaloceanspaces.com
> 
> Please explain your original issue in more detail, it looks like you're using the same filesystem config for all three storage folders, in which case your described behaviour would be expected.

@LukeTowers I use digitalocean space to store files, which compatiable with AWS s3, and I use a CDN url for static files by `'path'   => env('FILESYSTEM_ROOT_URL', '/storage/app/') . 'resized',` the environment variable `FILESYSTEM_ROOT_URL` is look like `https://my-cdn-domain.com/project-path/`. 

The `uploads` and `media` files use the correct CDN url, but `resized` files are not, it still use the original url like `https://<my-bucket-name>.<digitalocean-spalce-region>.digitaloceanspaces.com/project-path/resized/xxxx`, the except url should like `https://my-cdn-domain.com/project-path/resized/xxxx` which I setted by `app.storage.resized.path`.

**Comment by everyx** [comment]
@LukeTowers Maybe this line should be as below?
```php
            $resizedPath = rtrim(config('cms.storage.resized.path', '/storage/app/resized'), '/');
            $resizedFolder = config('cms.storage.resized.folder', 'resized');
            $url = $resizedPath . '/' . ltrim($this->getPathToResizedImage(), $resizedFolder);
```

https://github.com/octobercms/october/blob/2108321d49c4ed96b20b28cc0034445f2d5010b6/modules/system/classes/ImageResizer.php#L520

**Comment by LukeTowers** [comment]
@everyx ah, I see the issue. The `path` option is just used for identifying already resized images, it's not to be used for generating URLs to the resized image, that is rightfully handled by asking the storage disk to do that. See https://github.com/octobercms/october/blob/2108321d49c4ed96b20b28cc0034445f2d5010b6/modules/system/classes/ImageResizer.php#L34-L36 for the path explanation for the ImageResizer.

What you should do is set the `'url'` property on your `digitalocean` filesystem storage disk configuration.

So filesystems.php would look like

```php
'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
            'url'    => '/storage/app',
        ],

        'digitalocean' => [
            'driver'   => 'do_spaces',
            'url'        => env('FILESYSTEM_ROOT_URL', '/storage/app/'),
            'key'      => env('FILESYSTEM_DO_KEY', 'your-key'),
            'secret' => env('FILESYSTEM_DO_SECRET', 'your-secret'),
            'region' => env('FILESYSTEM_DO_REGION', 'your-region'),
            'space' => env('FILESYSTEM_DO_SPACE', 'your-space'),
        ],

    ],
```

See also https://laravel.com/docs/8.x/filesystem#url-host-customization

**Comment by everyx** [comment]
> @everyx ah, I see the issue. The `path` option is just used for identifying already resized images, it's not to be used for generating URLs to the resized image, that is rightfully handled by asking the storage disk to do that. See
> 
> https://github.com/octobercms/october/blob/2108321d49c4ed96b20b28cc0034445f2d5010b6/modules/system/classes/ImageResizer.php#L34-L36
> 
> for the path explanation for the ImageResizer.
> What you should do is set the `'url'` property on your `digitalocean` filesystem storage disk configuration.
> 
> So filesystems.php would look like
> 
> ```
> 'disks' => [
> 
>         'local' => [
>             'driver' => 'local',
>             'root'   => storage_path('app'),
>             'url'    => '/storage/app',
>         ],
> 
>         'digitalocean' => [
>             'driver'   => 'do_spaces',
>             'url'        => env('FILESYSTEM_ROOT_URL', '/storage/app/'),
>             'key'      => env('FILESYSTEM_DO_KEY', 'your-key'),
>             'secret' => env('FILESYSTEM_DO_SECRET', 'your-secret'),
>             'region' => env('FILESYSTEM_DO_REGION', 'your-region'),
>             'space' => env('FILESYSTEM_DO_SPACE', 'your-space'),
>         ],
> 
>     ],
> ```
> 
> See also https://laravel.com/docs/8.x/filesystem#url-host-customization

@LukeTowers This solved my problem, thanks. ;)

**Comment by everyx** [comment]
@LukeTowers I found another prolem, when I set disk.s3.url, I get a empty media library on backend, this below is my config:

cms.php

```php
    'storage' => [

        'uploads' => [
            'disk'            => env('FILESYSTEM_DEFAULT', 'local'),
            'folder'          => env('FILESYSTEM_FOLDER', '') . 'uploads',
            'path'            => env('FILESYSTEM_PATH', '/storage/app') . '/uploads',
            'temporaryUrlTTL' => 3600,
        ],

        'media' => [
            'disk'   => env('FILESYSTEM_DEFAULT', 'local'),
            'folder' => env('FILESYSTEM_FOLDER', '') . 'media',
            'path'   => env('FILESYSTEM_PATH', '/storage/app') . '/media',
        ],

        'resized' => [
            'disk'   => env('FILESYSTEM_DEFAULT', 'local'),
            'folder' => env('FILESYSTEM_FOLDER', '') . 'resized',
            'path'   => env('FILESYSTEM_PATH', '/storage/app') . '/resized',
        ],

    ],
```

filesystems.php

```php
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
            'url'    => '/storage/app',
        ],

        's3' => [
            'driver'     => 's3',
            'key'        => env('FILESYSTEM_S3_KEY', 'your-key'),
            'secret'     => env('FILESYSTEM_S3_SECRET', 'your-secret'),
            'endpoint'   => env('FILESYSTEM_S3_ENDPOINT', 'your-endpoint'),
            'region'     => env('FILESYSTEM_S3_REGION', 'your-region'),
            'bucket'     => env('FILESYSTEM_S3_BUCKET', 'your-bucket'),
            'url'        => env('FILESYSTEM_S3_URL', '/storage/app/'),
            'visibility' => 'public',
        ],
    ],
```

the `FILESYSTEM_PATH` is `https://cdn.mydomain.com/my-project`, and no matter if I set `FILESYSTEM_S3_URL` to `https://cdn.mydomain.com` or `https://cdn.mydomain.com/my-project`, the media library still empty

**Comment by LukeTowers** [comment]
@everyx submit a separate issue for that with your configuration from cms.php and filesystems.php and a screenshot of the empty media library and a screenshot of the not-empty DO space.
