### ISSUE TITLE
Timezone still using UTC in DST

### ISSUE THREAD

**Issue by andysh-uk** [octobercms/october#5699]
I have an issue with the timezone in OctoberCMS 3.2.12 - it always seems to be using UTC.

I create a blog article with a publish date of "23rd September 2015" and time of 00:00:00 - which falls into daylight saving time.

In the backend admin panel, and on the frontend of the website, it displays as 22nd September 2015. This makes sense because 23/09/2015 00:00:00 is 22/09/2015 23:00:00 in UTC.

However, both my site and my user profile is set to use Europe/London to display dates, so I would have expected that UTC date would be converted back to Europe/London local time, which would be 23/09/2015 00:00:00.

My article's publish date:

![image](https://user-images.githubusercontent.com/12907944/216970350-1855991d-9040-49d6-a7e7-5cca1b69c57b.png)

In the backend listing page:

![image](https://user-images.githubusercontent.com/12907944/216970586-2f6f0df2-920d-499d-966b-202653d5fbf0.png)

In the frontend (results of a Tailor EntryRecord query):

![image](https://user-images.githubusercontent.com/12907944/216970810-156a7443-abcd-4f3d-a74b-d45eca57c79b.png)

My user configuration:

![image](https://user-images.githubusercontent.com/12907944/216970993-03e8a400-5ae5-4f55-ba78-2d273e4e2697.png)

My site configuration:

![image](https://user-images.githubusercontent.com/12907944/216971121-44ad6289-6356-4e7c-a4f5-ccc15ea4f184.png)

The timezone value in my app/config.php is UTC - the default, which Laravel recommends.

**Comment by daftspunk** [comment]
Hello, according to the Moment.js library, this is accurate. The confusion may come from the fact that the list of timezone's in the backend comes from PHP, while the implementation of timezone conversion comes from [Moment.js](https://momentjs.com/timezone/docs/).

For example, running this in the JS console produces +01:00:

```js
→ moment.tz("2022-09-23 00:00:00", "Europe/London").format('Z z')
← '+01:00 BST'
```

The conversion appears to show the same as OP (JS):

```js
→ moment
    .tz("2022-09-23 00:00:00", "YYYY-MM-DD HH:mm:ss", "Europe/London")
    .tz("UTC")
    .format();
← '2022-09-22T23:00:00Z'
```

Back in PHP land we see (+00:00):

```php
> (new DateTimeZone("Europe/London"))->getOffset(new DateTime('now', new DateTimeZone('UTC')));
= 0 // +00:00
```

Perhaps someone closer to this can offer an explanation. I suspect it relates to British Summer Time, where JS is operating on more information than PHP.

**Comment by andysh-uk** [comment]
The time stored in the database is accurate - that date is 23:00 the day before in UTC.

For me the bug is that the date the user enters and the date displayed afterwards is different because the app presents the UTC date back to the user, and not converting it back to the user/site timezone.

E.g.:

* user enters 23/09/2023 00:00:00 (Europe/London timezone)
* stored in the DB as UTC 22/09/2023 23:00 (correct)
* displayed back to the user as 22/09/2023 (incorrect)

After loading from the database, it should be converted back to Europe/London, resulting in 23/09/2023 00:00:00 and therefore displaying as 23/09/2023 to the user.

**Comment by daftspunk** [comment]
Hey @andysh-uk 

Thanks for the follow up. Turns out this was a bug where timezones were not applied to the column. It should be fixed in v3.2.22. Once released, try updating to this version and if there are any further issues, just mention my username and we can take another look.

Thanks!

**Comment by andysh-uk** [comment]
Hey @daftspunk

Thanks for the quick resolution - it's much appreciated!  Looks perfect in the back-end.

The times still show as UTC in the front-end (understandable.) It's a simple case of passing the site's timezone to the Twig `date` filter:

For an article published at 23/09/2015 00:00:00, before - shows UTC:

```
{{ article.published_at_date|date('l, jS F, Y') }}

// Tuesday, 22nd September, 2015
```

After - shows in the site's timezone:

```
{{ article.published_at_date|date('l, jS F, Y', this.site.timezone) }}

// Wednesday, 23rd September, 2015
```

**Comment by daftspunk** [comment]
Hey @andysh-uk 

No worries! The `{{ carbon() }}` function will also automatically convert to the current timezone. Here's a link: https://docs.octobercms.com/3.x/markup/function/carbon.html
