### ISSUE TITLE
 Model   does not contain a definition after updating to 3.6.27

### ISSUE THREAD

**Issue by DaZOr93** [octobercms/october#5811]
The Buddies plugin was extended to add projects to the user. Everything worked on version 3.5.27, but after updating to version, it stopped adding projects to the user, and an error appears.

 Model 'Palmo\UserProjects\Models\UserProject' does not contain a definition for  'user_projects'

<img width="1087" alt="Снимок экрана 2024-07-30 в 13 28 03" src="https://github.com/user-attachments/assets/d2f43c00-5c8a-496b-ac6a-e4bd47eb4077">

```
<?php namespace Palmo\UserProjects\Models;

use Lovata\Buddies\Models\User;
use Model;

/**
 * UserProject Model
 *
 * @link https://docs.octobercms.com/3.x/extend/system/models.html
 */
class UserProject extends Model
{
    use \October\Rain\Database\Traits\Validation;
    use \Tailor\Traits\BlueprintRelationModel;

    /**
     * @var string table name
     */
    public $table = 'palmo_userprojects_user_projects';

    /**
     * @var array rules for validation
     */
    public $rules = [
        'investment_size' => 'required|numeric|min:1',
        'start_cost' => 'required|numeric|min:1',
//        'project_id' =>'unique:palmo_userproject_user_projects,user_id,1'
    ];

    public $belongsTo = [
        'user' => [User::class],
        'project' => [
            \Tailor\Models\EntryRecord::class,
            'blueprint' => '770d7f99-6513-4f12-a962-701630c2a45d'
        ],
    ];

    public $fillable = [
        'project_id',
        'user_id',
        'investment_size'
    ];

    public $attachMany = ['documents' => ['System\Models\File']];
}

```

```
<?php namespace Palmo\UserProjects;

use Backend;
use System\Classes\PluginBase;
use Lovata\Buddies\Models\User as UserModel;
use Lovata\Buddies\Controllers\Users as UserController;

/**
 * Plugin Information File
 *
 * @link https://docs.octobercms.com/3.x/extend/system/plugins.html
 */
class Plugin extends PluginBase
{
    /**
     * pluginDetails about this plugin.
     */
    public function pluginDetails()
    {
        return [
            'name' => 'UserProjects',
            'description' => 'No description provided yet...',
            'author' => 'Palmo',
            'icon' => 'icon-leaf'
        ];
    }

    /**
     * register method, called when the plugin is first registered.
     */
    public function register()
    {
        //
    }

    /**
     * boot method, called right before the request route.
     */
    public function boot()
    {
        UserModel::extend(function ($model){
            $model->hasMany['user_projects'] = ['Palmo\UserProjects\Models\UserProject'];
            $model->addCachedField(['user_projects']);

        });
        UserController::extendFormFields(function ($form, $model, $contex){

            $form->addTabFields([
                "user_projects" =>[
                    "label"=> "Проекты",
                    "tab"=>"Проекты",
                    'type' => 'relation',
                    'controller' => [
                        'label'=>'Проект',
                        'view'=>[
                            'list' =>'$/palmo/userprojects/models/userproject/columns.yaml',
                            'recordsPerPage'=>10,

                        ],
                        'manage'=>[
                            'form' =>'$/palmo/userprojects/models/userproject/fields.yaml',
                        ],
                    ]
                ]
            ]);
        });
    }

```

**Comment by daftspunk** [comment]
Hi @DaZOr93 

Try clearing the browser cache, it should solve it.

**Comment by DaZOr93** [comment]
I executed the command php artisan cache:clear and entered the browser's incognito mode, but the problem was not resolved.

**Comment by DaZOr93** [comment]
> Hi @DaZOr93
> 
> Try clearing the browser cache, it should solve it.

I executed the command php artisan cache:clear and entered the browser's incognito mode, but the problem was not resolved.

**Comment by daftspunk** [comment]
This error is a known issue related to a stale JavaScript file. Try running `composer update` to request the files again and restart the web server in case it is being cached there.

**Comment by daftspunk** [comment]
One other thing to check, make sure this returns `true`:

```php
(new \Lovata\Buddies\Models\User)->hasRelation('user_projects');
```

This is the check used in PHP for this specific error message.

**Comment by DaZOr93** [comment]
> This error is a known issue related to a stale JavaScript file. Try running `composer update` to request the files again and restart the web server in case it is being cached there.


did not help


> ```
> (new \Lovata\Buddies\Models\User)->hasRelation('user_projects');
> ```

 
```
 public function boot()
    {
        UserModel::extend(function ($model){
            $model->hasMany['user_projects'] = ['Palmo\UserProjects\Models\UserProject'];
            $model->addCachedField(['user_projects']);

        });

        dd((new \Lovata\Buddies\Models\User)->hasRelation('user_projects'));

        UserController::extendFormFields(function ($form, $model, $contex){

            $form->addTabFields([
                "user_projects" =>[
                    "label"=> "Проекты",
                    "tab"=>"Проекты",
                    'type' => 'relation',
                    'controller' => [
                        'label'=>'Проект',
                        'view'=>[
                            'list' =>'$/palmo/userprojects/models/userproject/columns.yaml',
                            'recordsPerPage'=>10,

                        ],
                        'manage'=>[
                            'form' =>'$/palmo/userprojects/models/userproject/fields.yaml',
                        ],
                    ]
                ]
            ]);
        });
    }
```

  
 returns true

**Comment by daftspunk** [comment]
Thank you for confirming and checking for the known issue.

I have reproduced this in the Test plugin with the following code:

```php
\RainLab\User\Models\User::extend(function($model) {
    $model->hasMany['products'] = \October\Test\Models\Product::class;
});

\RainLab\User\Controllers\Users::extendFormFields(function ($form, $model, $context){
    $form->addTabFields([
        "products" =>[
            "label"=> "Products",
            "tab"=>"Products",
            'type' => 'relation',
            'controller' => [
                'label'=>'Product',
                'view'=>[
                    'list' =>'$/october/test/models/product/columns.yaml',
                    'recordsPerPage'=>10,

                ],
                'manage'=>[
                    'form' =>'$/october/test/models/product/fields.yaml',
                ],
            ]
        ]
    ]);
});
```

I will let you know once we have a result.

**Comment by daftspunk** [comment]
Hi @DaZOr93 

We have completed the investigation on this. The reason it occurs is the form is extended twice, once for the `User` model and once for the `UserProject` model. This is because using the `relation` form widget with the `controller` type injects another form in to the controller.

To solve this, add a instance check to the model.

```php
UserController::extendFormFields(function ($form, $model, $context) {
    // Solution: Add this check
    if (!$model instanceof UserModel) {
        return;
    }

    $form->addTabFields([...]);
});
```

I hope this helps.

**Comment by DaZOr93** [comment]
> Привет@DaZOr93
> 
> Мы завершили расследование по этому вопросу. Причина этого в том, что форма расширяется дважды, один раз для модели `User`и один раз для `UserProject`модели. Это происходит потому, что использование `relation`виджета формы с `controller`типом внедряет другую форму в контроллер.
> 
> Чтобы решить эту проблему, добавьте в модель проверку экземпляра.
> 
> ```
> UserController::extendFormFields(function ($form, $model, $context) {
>     // Solution: Add this check
>     if (!$model instanceof UserModel) {
>         return;
>     }
> 
>     $form->addTabFields([...]);
> });
> ```
> 
> Надеюсь, это поможет.

Thank you, this solved my problem. Is this a temporary or permanent solution? Also, it solved another issue I had. When adding/editing a project, there was a table showing the user's projects, and from there, it was possible to click to create a project, opening a new window, and this could be done endlessly.


octobercms 3.5.27 before applying your solution

<img width="900" alt="Снимок экрана 2024-08-02 в 11 10 18" src="https://github.com/user-attachments/assets/71b2b05d-05d1-48d9-bc4b-19291c8387bc">
<img width="1079" alt="Снимок экрана 2024-08-02 в 11 18 02" src="https://github.com/user-attachments/assets/f269bcec-7574-439a-ad81-eb58cc99bae5">


octobercms 3.5.27 and 3.6.27 after applying your solution
<img width="905" alt="Снимок экрана 2024-08-02 в 11 08 47" src="https://github.com/user-attachments/assets/0caa211a-6ccc-48fc-8e0d-66a353558f92">

**Comment by daftspunk** [comment]
> Is this a temporary or permanent solution?

It is the solution to the problem that you've described.

> When adding/editing a project, there was a table showing the user's projects, and from there, it was possible to click to create a project, opening a new window, and this could be done endlessly.

To make this possible, the UserProject model needs a UserProject relation to overcome the "user_project" is missing error. And also, you wouldn't need the first solution any more.

I hope this helps.
